### ISSUE TITLE
* BUG *

### ISSUE THREAD

**Issue by AdTokens** [Hdactech/hdac#5]
**### VERY IMPORTANT!!**

Hello, I've found a very important bug. Review these transactions. It's not clear who sent the coins in some of these transactions. Also in some transactions paid a very high transfer fee. What are these miners trying to do? Please review this bug.

**Who is senders?????????????????????????????????????????????**

https://i.imgur.com/v0GInYv.png

**Address:** HSAq11NRpdWGKn2TapJZdY7Yg8vNZ1PH5a
**Hdacexplorer:** https://explorer.eu.hdactech.com/hdac-explorer/address/HSAq11NRpdWGKn2TapJZdY7Yg8vNZ1PH5a

- **TX1:** https://explorer.eu.hdactech.com/hdac-explorer/tx/1d93ca772c86fe096dd251678cdea80c8e89a596f3af6c621d76889e14a4231b

**Address:** HJ2mxPFTx4gz9anVA1oMmJTeBb3NXkoDDV
**Hdacexplorer:** https://explorer.eu.hdactech.com/hdac-explorer/address/HJ2mxPFTx4gz9anVA1oMmJTeBb3NXkoDDV

- **TX1:** https://explorer.eu.hdactech.com/hdac-explorer/tx/a9081b51d55193427baeb8c8f8901205980bed505fdc02d0087cc904359c2cf5
- **TX2:** https://explorer.eu.hdactech.com/hdac-explorer/tx/a5645374d43e26698dad568b7bf8b15821db729312e37a93da5802911c90813d
- **TX3:** https://explorer.eu.hdactech.com/hdac-explorer/tx/c301a7e961f9b8e72a54845849286a9e0eb08e05a82864090d212b760ebaf2d1
- **TX4:** https://explorer.eu.hdactech.com/hdac-explorer/tx/737ab44138a07f5d5862c4c448a7e5a2ac6726e9e22ba8f7af93d0a4d5ec3649
- **TX5:** https://explorer.eu.hdactech.com/hdac-explorer/tx/792209a07c985536fccd7b8ed7a5092f7815b43e6aeb6b28d96c3f27bc1f51fd

**Address:** HERtkDYb9qtP3Hx6eGa1WJjXETjCobTjtq
**Hdacexplorer:** https://explorer.eu.hdactech.com/hdac-explorer/address/HERtkDYb9qtP3Hx6eGa1WJjXETjCobTjtq

- **TX1:** https://explorer.eu.hdactech.com/hdac-explorer/tx/31030e13d4f485091dd1e3ad89e1343984ec406c4c4390637fdc57f7885d6998
- **TX2:** https://explorer.eu.hdactech.com/hdac-explorer/tx/ddb284a9ac261d7548579d0011151b7a982b628bc64cbbb9de73c28eeb014630
- **TX3:** https://explorer.eu.hdactech.com/hdac-explorer/tx/4df98938dd93178ea3cda9a2cd84b41b1a6f088803e2807d20c2790c4a5086aa

I think the problem is in Hdac Explorer.
For example:

**EU Link**
https://explorer.eu.hdactech.com/hdac-explorer/tx/1d93ca772c86fe096dd251678cdea80c8e89a596f3af6c621d76889e14a4231b

**AS Link**
https://explorer.as.hdactech.com/hdac-explorer/tx/1d93ca772c86fe096dd251678cdea80c8e89a596f3af6c621d76889e14a4231b

**My Hdac address:** HPFDgKQeFXdkzxfY4EgHD3WcWy8pdrEWLi
**Telegram:** @XhearthmeagN

**Comment by AdTokens** [comment]
I think the problem is in Hdac Explorer.

For example:

**EU Link**
https://explorer.eu.hdactech.com/hdac-explorer/tx/1d93ca772c86fe096dd251678cdea80c8e89a596f3af6c621d76889e14a4231b

**AS Link**
https://explorer.as.hdactech.com/hdac-explorer/tx/1d93ca772c86fe096dd251678cdea80c8e89a596f3af6c621d76889e14a4231b

**Comment by jason0627** [comment]
Dear AdTokens,

**Comment by HdacTechTeam** [comment]
Hello, This is Hdac Technology.

The issue in regards to Hdac explorer has been resolved. 
Thanks for the pointing out the issue and there will be a small compensation given, which we will let you know the detail via Telegram. 

Thanks.

**Comment by AdTokens** [comment]
The problem is still continuing. There is a difference between Europe Explorer and Asia Explorer.

AS Block #138388 mined by HVWwcaW3meffJfqzeP2L9XWoFYNFHFmzhA

EU Block #138388 mined by H8WabmtbrfpNzfJCgBbMQ2UJB2duiCrM3m

Explorer doesn’t synchronize with each other. Does this mean it's a hardfork? Or is the problem in Hdac Explorer?

https://explorer.eu.hdactech.com/hdac-explorer/block/5e59407ca87609fa32811c54100b4f41f8622a9f79ed7c38ebca50bf6968f882

https://explorer.as.hdactech.com/hdac-explorer/block/aceea4214d715f29f014fbe53bfa34ad0f985a174c7c99861dc802933106c8aa
